### ISSUE TITLE
Blocked a cleartext HTTP

### ISSUE THREAD

**Issue by Meravici** [MadViper/FreeUni-Swift-2015-Final-Project---Event#6]
სურათს ქსელიდან ვერ ვტვირთავთ, გვიგდებს ამ ერორს:
```
App Transport Security has blocked a cleartext HTTP (http://) resource load since
it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
```

გადმოწერას ამ კოდით ვაკეთებთ
```swift
dispatch_async(dispatch_get_global_queue(Int(QOS_CLASS_USER_INITIATED.rawValue), 0)) {
    if let data = NSData(contentsOfURL: url) {
        dispatch_async(dispatch_get_main_queue()) {
            self.img.image = UIImage(data: data)
        }
    }
}
```
სურათი ამ ურიზეა: http://www.flint-group.com/wp-content/uploads/2014/05/fb_event_a.jpg

@jibla ხომ არ იცი რა უნდა ვუშველოთ?

**Comment by jibla** [comment]
ვიცი

**Comment by jibla** [comment]
გითხრათ?

**Comment by jibla** [comment]
<key>NSAppTransportSecurity</key>
    <dict>
      
      <key>NSAllowsArbitraryLoads</key>
          <true/>
    </dict>


ეს ჩაამატეთ info.plist-ში.
ეგ მესიჯი ისე მთლიანად რო დაგეგუგლათ პირველივე result-ში იპოვიდით პასუხს.

**Comment by MadViper** [comment]
thanx
